export interface BoneData {
  id: string;
  name: string;
  latinName: string;
  group: 'head' | 'torso' | 'forelimb' | 'hindlimb';
  position: [number, number, number];
  rotation: [number, number, number];
  scale: [number, number, number];
  shape: 'box' | 'cylinder' | 'sphere' | 'cone';
  discoveryYear: string;
  discoverer: string;
  description: string;
  function: string;
}

export const boneGroups = {
  head: { name: '头部骨骼', icon: '🦴' },
  torso: { name: '躯干骨骼', icon: '🦴' },
  forelimb: { name: '前肢骨骼', icon: '🦴' },
  hindlimb: { name: '后肢骨骼', icon: '🦴' },
};

export const bones: BoneData[] = [
  // 头部 - 7块
  {
    id: 'skull',
    name: '头骨',
    latinName: 'Cranium',
    group: 'head',
    position: [0, 4.5, 0],
    rotation: [0, 0, 0],
    scale: [1.2, 0.9, 1.8],
    shape: 'box',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '霸王龙的头骨巨大而坚固，长度可达1.5米，具有强壮的颌骨结构。',
    function: '保护大脑和感觉器官，提供强大的咬合力支撑。',
  },
  {
    id: 'jaw-lower',
    name: '下颌骨',
    latinName: 'Mandibula',
    group: 'head',
    position: [0, 3.9, 0.2],
    rotation: [0, 0, 0],
    scale: [1.0, 0.3, 1.5],
    shape: 'box',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '下颌骨与头骨相连，布满锋利的圆锥形牙齿。',
    function: '支撑牙齿，配合上颌完成咬合动作。',
  },
  {
    id: 'maxilla-left',
    name: '左上颌骨',
    latinName: 'Maxilla sinistra',
    group: 'head',
    position: [-0.5, 4.2, 0.1],
    rotation: [0, 0, 0.1],
    scale: [0.15, 0.4, 1.2],
    shape: 'box',
    discoveryYear: '1905',
    discoverer: 'Henry Fairfield Osborn',
    description: '上颌骨两侧对称，构成鼻腔和眼眶的侧壁。',
    function: '支撑牙齿，构成面部侧面轮廓。',
  },
  {
    id: 'maxilla-right',
    name: '右上颌骨',
    latinName: 'Maxilla dextra',
    group: 'head',
    position: [0.5, 4.2, 0.1],
    rotation: [0, 0, -0.1],
    scale: [0.15, 0.4, 1.2],
    shape: 'box',
    discoveryYear: '1905',
    discoverer: 'Henry Fairfield Osborn',
    description: '上颌骨两侧对称，构成鼻腔和眼眶的侧壁。',
    function: '支撑牙齿，构成面部侧面轮廓。',
  },
  {
    id: 'nasal',
    name: '鼻骨',
    latinName: 'Os nasale',
    group: 'head',
    position: [0, 4.6, 0.6],
    rotation: [0, 0, 0],
    scale: [0.3, 0.15, 0.8],
    shape: 'box',
    discoveryYear: '1908',
    discoverer: 'Barnum Brown',
    description: '鼻骨位于头骨前端，构成鼻腔顶部。',
    function: '保护嗅觉器官，构成鼻孔上缘。',
  },
  {
    id: 'frontal',
    name: '额骨',
    latinName: 'Os frontale',
    group: 'head',
    position: [0, 4.7, -0.2],
    rotation: [0.1, 0, 0],
    scale: [0.8, 0.1, 0.6],
    shape: 'box',
    discoveryYear: '1905',
    discoverer: 'Henry Fairfield Osborn',
    description: '额骨构成头骨的上部和眼眶上缘。',
    function: '保护大脑前部，形成眼眶上缘。',
  },
  {
    id: 'occipital',
    name: '枕骨',
    latinName: 'Os occipitale',
    group: 'head',
    position: [0, 4.3, -0.9],
    rotation: [0.3, 0, 0],
    scale: [0.6, 0.5, 0.2],
    shape: 'box',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '枕骨位于头骨后部，与第一颈椎相连。',
    function: '保护大脑后部，连接头骨与脊柱。',
  },

  // 躯干 - 8块
  {
    id: 'cervical-1',
    name: '第一颈椎',
    latinName: 'Vertebra cervicalis I',
    group: 'torso',
    position: [0, 3.8, -0.8],
    rotation: [0.2, 0, 0],
    scale: [0.4, 0.25, 0.5],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '第一颈椎又称寰椎，与枕骨髁相关节。',
    function: '支撑头骨，允许头部做点头动作。',
  },
  {
    id: 'cervical-3',
    name: '第三颈椎',
    latinName: 'Vertebra cervicalis III',
    group: 'torso',
    position: [0, 3.4, -1.0],
    rotation: [0.4, 0, 0],
    scale: [0.45, 0.3, 0.55],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '颈椎短而粗壮，支持大型头部。',
    function: '连接头部与躯干，提供颈部灵活性。',
  },
  {
    id: 'thoracic-5',
    name: '第五胸椎',
    latinName: 'Vertebra thoracica V',
    group: 'torso',
    position: [0, 2.8, -1.5],
    rotation: [0.5, 0, 0],
    scale: [0.6, 0.4, 0.7],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '胸椎粗壮，连接肋骨，支撑胸腔。',
    function: '支撑躯干，为肋骨提供附着点。',
  },
  {
    id: 'thoracic-10',
    name: '第十胸椎',
    latinName: 'Vertebra thoracica X',
    group: 'torso',
    position: [0, 2.2, -2.2],
    rotation: [0.6, 0, 0],
    scale: [0.7, 0.45, 0.8],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '后部胸椎更加粗壮，支撑后肢肌肉。',
    function: '传递后肢力量，支撑身体重量。',
  },
  {
    id: 'sacrum',
    name: '荐骨',
    latinName: 'Os sacrum',
    group: 'torso',
    position: [0, 1.6, -2.8],
    rotation: [0.7, 0, 0],
    scale: [0.8, 0.5, 1.0],
    shape: 'box',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '荐骨由多块椎骨愈合而成，连接腰带。',
    function: '将后肢力量传递到脊柱，支撑身体。',
  },
  {
    id: 'rib-left',
    name: '左侧肋骨',
    latinName: 'Costa sinistra',
    group: 'torso',
    position: [-0.8, 2.6, -1.5],
    rotation: [0.3, 0.2, 0.5],
    scale: [0.1, 1.5, 0.3],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '肋骨弯曲呈弧形，构成胸腔侧壁。',
    function: '保护内脏，协助呼吸运动。',
  },
  {
    id: 'rib-right',
    name: '右侧肋骨',
    latinName: 'Costa dextra',
    group: 'torso',
    position: [0.8, 2.6, -1.5],
    rotation: [0.3, -0.2, -0.5],
    scale: [0.1, 1.5, 0.3],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '肋骨弯曲呈弧形，构成胸腔侧壁。',
    function: '保护内脏，协助呼吸运动。',
  },
  {
    id: 'scapula',
    name: '肩胛骨',
    latinName: 'Scapula',
    group: 'torso',
    position: [-0.9, 3.0, -1.0],
    rotation: [0.2, 0.3, 0.4],
    scale: [0.2, 1.2, 0.6],
    shape: 'box',
    discoveryYear: '1905',
    discoverer: 'Henry Fairfield Osborn',
    description: '肩胛骨相对较小，连接前肢与躯干。',
    function: '为前肢肌肉提供附着点。',
  },

  // 前肢 - 4块
  {
    id: 'humerus-left',
    name: '左肱骨',
    latinName: 'Humerus sinister',
    group: 'forelimb',
    position: [-1.2, 2.2, -0.8],
    rotation: [0.5, 0.2, 0.3],
    scale: [0.25, 0.8, 0.25],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '肱骨非常短小，与巨大的身体形成鲜明对比。',
    function: '前肢主要骨骼，可能用于抓取或平衡。',
  },
  {
    id: 'humerus-right',
    name: '右肱骨',
    latinName: 'Humerus dexter',
    group: 'forelimb',
    position: [1.2, 2.2, -0.8],
    rotation: [0.5, -0.2, -0.3],
    scale: [0.25, 0.8, 0.25],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '肱骨非常短小，与巨大的身体形成鲜明对比。',
    function: '前肢主要骨骼，可能用于抓取或平衡。',
  },
  {
    id: 'radius-left',
    name: '左桡骨',
    latinName: 'Radius sinister',
    group: 'forelimb',
    position: [-1.3, 1.6, -0.6],
    rotation: [0.3, 0.1, 0.2],
    scale: [0.15, 0.5, 0.15],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '桡骨更加细小，是前肢的第二根长骨。',
    function: '支撑前臂，辅助前肢运动。',
  },
  {
    id: 'radius-right',
    name: '右桡骨',
    latinName: 'Radius dexter',
    group: 'forelimb',
    position: [1.3, 1.6, -0.6],
    rotation: [0.3, -0.1, -0.2],
    scale: [0.15, 0.5, 0.15],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '桡骨更加细小，是前肢的第二根长骨。',
    function: '支撑前臂，辅助前肢运动。',
  },

  // 后肢 - 7块
  {
    id: 'femur-left',
    name: '左股骨',
    latinName: 'Femur sinistrum',
    group: 'hindlimb',
    position: [-0.9, 1.0, -2.5],
    rotation: [0.8, 0.1, 0.1],
    scale: [0.35, 1.8, 0.35],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '股骨粗壮强大，是后肢的主要承重骨。',
    function: '支撑全身重量，提供行走和奔跑的动力。',
  },
  {
    id: 'femur-right',
    name: '右股骨',
    latinName: 'Femur dextrum',
    group: 'hindlimb',
    position: [0.9, 1.0, -2.5],
    rotation: [0.8, -0.1, -0.1],
    scale: [0.35, 1.8, 0.35],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '股骨粗壮强大，是后肢的主要承重骨。',
    function: '支撑全身重量，提供行走和奔跑的动力。',
  },
  {
    id: 'tibia-left',
    name: '左胫骨',
    latinName: 'Tibia sinistra',
    group: 'hindlimb',
    position: [-0.9, -0.6, -2.0],
    rotation: [0.6, 0.1, 0.1],
    scale: [0.28, 1.4, 0.28],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '胫骨长而结实，是小腿的主要骨骼。',
    function: '传递体重到足部，参与后肢屈伸。',
  },
  {
    id: 'tibia-right',
    name: '右胫骨',
    latinName: 'Tibia dextra',
    group: 'hindlimb',
    position: [0.9, -0.6, -2.0],
    rotation: [0.6, -0.1, -0.1],
    scale: [0.28, 1.4, 0.28],
    shape: 'cylinder',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '胫骨长而结实，是小腿的主要骨骼。',
    function: '传递体重到足部，参与后肢屈伸。',
  },
  {
    id: 'fibula-left',
    name: '左腓骨',
    latinName: 'Fibula sinistra',
    group: 'hindlimb',
    position: [-1.1, -0.6, -1.9],
    rotation: [0.6, 0.15, 0.1],
    scale: [0.12, 1.3, 0.12],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '腓骨较细，位于胫骨外侧。',
    function: '辅助支撑小腿，为肌肉提供附着点。',
  },
  {
    id: 'fibula-right',
    name: '右腓骨',
    latinName: 'Fibula dextra',
    group: 'hindlimb',
    position: [1.1, -0.6, -1.9],
    rotation: [0.6, -0.15, -0.1],
    scale: [0.12, 1.3, 0.12],
    shape: 'cylinder',
    discoveryYear: '1903',
    discoverer: 'Barnum Brown',
    description: '腓骨较细，位于胫骨外侧。',
    function: '辅助支撑小腿，为肌肉提供附着点。',
  },
  {
    id: 'metatarsal-left',
    name: '左跖骨',
    latinName: 'Os metatarsale sinistrum',
    group: 'hindlimb',
    position: [-0.9, -1.5, -1.2],
    rotation: [0.3, 0.1, 0.1],
    scale: [0.2, 0.6, 0.4],
    shape: 'box',
    discoveryYear: '1902',
    discoverer: 'Barnum Brown',
    description: '跖骨愈合形成粗壮的足部结构。',
    function: '支撑身体重量，缓冲行走时的冲击力。',
  },
];

export const getBonesByGroup = (group: string): BoneData[] => {
  return bones.filter((bone) => bone.group === group);
};

export const getBoneById = (id: string): BoneData | undefined => {
  return bones.find((bone) => bone.id === id);
};

export const groupCameraPositions: Record<string, [number, number, number]> = {
  head: [0, 5, 8],
  torso: [0, 2.5, 8],
  forelimb: [-2, 2, 8],
  hindlimb: [0, -0.5, 8],
};
