import type { Ingredient, Recipe } from './types';
import { hexToRgb } from './types';

export const INGREDIENTS: Ingredient[] = [
  {
    id: 'fire_dust',
    name: '火焰粉尘',
    color: '#FF6F00',
    glow: '#FF6F00',
    rgb: hexToRgb('#FF6F00'),
  },
  {
    id: 'ice_shard',
    name: '冰晶碎片',
    color: '#00BFFF',
    glow: '#00BFFF',
    rgb: hexToRgb('#00BFFF'),
  },
  {
    id: 'love_essence',
    name: '魅情精华',
    color: '#FF1493',
    glow: '#FF1493',
    rgb: hexToRgb('#FF1493'),
  },
  {
    id: 'forest_leaf',
    name: '森之绿叶',
    color: '#32CD32',
    glow: '#32CD32',
    rgb: hexToRgb('#32CD32'),
  },
  {
    id: 'void_ink',
    name: '虚空墨汁',
    color: '#6A0DAD',
    glow: '#9B30FF',
    rgb: hexToRgb('#6A0DAD'),
  },
  {
    id: 'sun_stone',
    name: '太阳石粉',
    color: '#FFD700',
    glow: '#FFD700',
    rgb: hexToRgb('#FFD700'),
  },
  {
    id: 'moon_dew',
    name: '月光露珠',
    color: '#C0C0C0',
    glow: '#E8E8E8',
    rgb: hexToRgb('#C0C0C0'),
  },
  {
    id: 'dragon_blood',
    name: '龙血结晶',
    color: '#B22222',
    glow: '#FF3030',
    rgb: hexToRgb('#B22222'),
  },
];

export const RECIPES: Recipe[] = [
  {
    id: 'flame',
    name: '烈焰药水',
    ingredientIds: ['fire_dust', 'sun_stone'],
    resultColor: '#FF4500',
    rgb: hexToRgb('#FF4500'),
    description: '燃烧着永恒之火的炽热药剂，饮下者可短时间内喷吐火焰。',
  },
  {
    id: 'frost',
    name: '冰霜药剂',
    ingredientIds: ['ice_shard', 'moon_dew'],
    resultColor: '#87CEFA',
    rgb: hexToRgb('#87CEFA'),
    description: '凝结了极寒月光的冰冷药水，触物即冻。',
  },
  {
    id: 'love',
    name: '魅惑之心',
    ingredientIds: ['love_essence', 'sun_stone'],
    resultColor: '#FF69B4',
    rgb: hexToRgb('#FF69B4'),
    description: '充满甜美气息的粉红色药剂，散发着无法抗拒的吸引力。',
  },
  {
    id: 'nature',
    name: '自然之息',
    ingredientIds: ['forest_leaf', 'moon_dew'],
    resultColor: '#228B22',
    rgb: hexToRgb('#228B22'),
    description: '蕴含古老森林力量的翠绿药剂，让枯木重新焕发生机。',
  },
  {
    id: 'shadow',
    name: '暗影潜行',
    ingredientIds: ['void_ink', 'moon_dew'],
    resultColor: '#4B0082',
    rgb: hexToRgb('#4B0082'),
    description: '漆黑如夜的神秘药剂，饮下者可融入阴影之中。',
  },
  {
    id: 'phoenix',
    name: '凤凰涅槃',
    ingredientIds: ['dragon_blood', 'fire_dust', 'sun_stone'],
    resultColor: '#FF2200',
    rgb: hexToRgb('#FF2200'),
    description: '传说中的不死药水，可让饮者在烈焰中重获新生。',
  },
  {
    id: 'aurora',
    name: '极光之舞',
    ingredientIds: ['ice_shard', 'love_essence', 'moon_dew'],
    resultColor: '#7FFFD4',
    rgb: hexToRgb('#7FFFD4'),
    description: '色彩流动如梦似幻，瓶中仿佛封存了一整片北极光。',
  },
  {
    id: 'toxic_love',
    name: '禁忌之恋',
    ingredientIds: ['love_essence', 'void_ink'],
    resultColor: '#9932CC',
    rgb: hexToRgb('#9932CC'),
    description: '甜美而致命的紫色药剂，爱与毁灭仅一线之隔。',
  },
  {
    id: 'forest_fire',
    name: '燎原之怒',
    ingredientIds: ['fire_dust', 'forest_leaf'],
    resultColor: '#D2691E',
    rgb: hexToRgb('#D2691E'),
    description: '燃烧的森林之力凝聚而成，散发着焦土与生机的矛盾气息。',
  },
  {
    id: 'holy_light',
    name: '圣光祝福',
    ingredientIds: ['sun_stone', 'moon_dew', 'forest_leaf'],
    resultColor: '#FFFFCC',
    rgb: hexToRgb('#FFFFCC'),
    description: '日月与自然合力铸就，散发神圣光辉的治愈药剂。',
  },
  {
    id: 'single_fire',
    name: '火舌之油',
    ingredientIds: ['fire_dust'],
    resultColor: '#FF6F00',
    rgb: hexToRgb('#FF6F00'),
    description: '单一火焰元素浓缩而成，涂抹于武器可使其燃烧。',
  },
  {
    id: 'single_ice',
    name: '寒冽精粹',
    ingredientIds: ['ice_shard'],
    resultColor: '#00BFFF',
    rgb: hexToRgb('#00BFFF'),
    description: '纯粹冰元素凝结而成，可用于冷却炽热的炼金器皿。',
  },
];
