SPECIES_DATA = {
    "ginkgo": {
        "id": "ginkgo",
        "name": "银杏",
        "nameEn": "Ginkgo",
        "thumbnail": "ginkgo",
        "description": "银杏科银杏属，落叶大乔木，扇形叶片，秋叶金黄",
        "lsystem": {
            "axiom": "F",
            "rules": [{"symbol": "F", "replacement": "FF+[+F-F-F]-[-F+F+F]"}],
            "angle": 25.7,
            "iterations": 4,
        },
        "branches": [
            {"angle": 25, "length": 1.0, "depth": 1},
            {"angle": 35, "length": 0.8, "depth": 2},
            {"angle": 20, "length": 0.6, "depth": 3},
            {"angle": 45, "length": 0.4, "depth": 4},
        ],
        "leaves": {
            "color": "#A8D5A2",
            "shape": "fan",
            "size": 0.3,
            "density": 0.8,
        },
        "growthRate": {
            "maxHeight": 10,
            "maxCrownWidth": 8,
            "yearsToMature": 30,
        },
        "seasonColors": {
            "spring": "#A8D5A2",
            "summer": "#4CAF50",
            "autumn": "#FFD700",
            "winter": "#9E9E9E",
        },
    },
    "oak": {
        "id": "oak",
        "name": "橡树",
        "nameEn": "Oak",
        "thumbnail": "oak",
        "description": "壳斗科栎属，落叶乔木，宽大树冠，坚硬木材",
        "lsystem": {
            "axiom": "F",
            "rules": [{"symbol": "F", "replacement": "F[+F]F[-F][F]"}],
            "angle": 20,
            "iterations": 5,
        },
        "branches": [
            {"angle": 30, "length": 1.2, "depth": 1},
            {"angle": 40, "length": 0.9, "depth": 2},
            {"angle": 35, "length": 0.7, "depth": 3},
            {"angle": 25, "length": 0.5, "depth": 4},
            {"angle": 50, "length": 0.3, "depth": 5},
        ],
        "leaves": {
            "color": "#4CAF50",
            "shape": "lobed",
            "size": 0.25,
            "density": 0.9,
        },
        "growthRate": {
            "maxHeight": 12,
            "maxCrownWidth": 10,
            "yearsToMature": 40,
        },
        "seasonColors": {
            "spring": "#7CB342",
            "summer": "#33691E",
            "autumn": "#FF6F00",
            "winter": "#795548",
        },
    },
    "pine": {
        "id": "pine",
        "name": "松树",
        "nameEn": "Pine",
        "thumbnail": "pine",
        "description": "松科松属，常绿乔木，针状叶，塔形树冠",
        "lsystem": {
            "axiom": "F",
            "rules": [{"symbol": "F", "replacement": "FF-[-F+F+F]+[+F-F-F]"}],
            "angle": 22.5,
            "iterations": 4,
        },
        "branches": [
            {"angle": 20, "length": 1.1, "depth": 1},
            {"angle": 15, "length": 0.85, "depth": 2},
            {"angle": 25, "length": 0.65, "depth": 3},
            {"angle": 10, "length": 0.5, "depth": 4},
        ],
        "leaves": {
            "color": "#2E7D32",
            "shape": "needle",
            "size": 0.2,
            "density": 1.0,
        },
        "growthRate": {
            "maxHeight": 15,
            "maxCrownWidth": 6,
            "yearsToMature": 50,
        },
        "seasonColors": {
            "spring": "#66BB6A",
            "summer": "#2E7D32",
            "autumn": "#558B2F",
            "winter": "#33691E",
        },
    },
    "maple": {
        "id": "maple",
        "name": "枫树",
        "nameEn": "Maple",
        "thumbnail": "maple",
        "description": "槭树科槭属，落叶乔木，掌状裂叶，秋叶红艳",
        "lsystem": {
            "axiom": "F",
            "rules": [{"symbol": "F", "replacement": "F[+F]F[-F]F"}],
            "angle": 25.7,
            "iterations": 4,
        },
        "branches": [
            {"angle": 35, "length": 0.9, "depth": 1},
            {"angle": 45, "length": 0.75, "depth": 2},
            {"angle": 30, "length": 0.55, "depth": 3},
            {"angle": 40, "length": 0.35, "depth": 4},
        ],
        "leaves": {
            "color": "#66BB6A",
            "shape": "palmate",
            "size": 0.28,
            "density": 0.85,
        },
        "growthRate": {
            "maxHeight": 9,
            "maxCrownWidth": 7,
            "yearsToMature": 25,
        },
        "seasonColors": {
            "spring": "#81C784",
            "summer": "#388E3C",
            "autumn": "#FF3D00",
            "winter": "#9E9E9E",
        },
    },
}
