import type { Work, MaterialPack, Order } from '../shared/types';
import { v4 as uuidv4 } from 'uuid';

export const works: Work[] = [
  {
    id: 'w001',
    title: '原色植鞣革短夹',
    description: '采用意大利进口原色植鞣革，纯手工缝线制作。随着使用时间推移，皮革会逐渐产生迷人的蜜色包浆，每一件都是独一无二的时光艺术品。适合日常随身携带，可放置6张卡片和少量现金。',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&h=400&fit=crop',
    tags: ['植鞣革', '原色', '手工缝线', '封边'],
  },
  {
    id: 'w002',
    title: '铬鞣革编织托特包',
    description: '精选法国小羊皮铬鞣革，搭配传统三股编织技法。包身柔软轻盈，内部空间宽敞，可容纳13寸笔记本电脑。适合通勤和日常购物使用。',
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&h=400&fit=crop',
    tags: ['铬鞣革', '编织', '封边', '手工缝线'],
  },
  {
    id: 'w003',
    title: '十字纹长夹',
    description: '十字纹牛皮纹理清晰，质感硬朗。长夹设计拥有12个卡位、2个隔层和1个拉链零钱包，功能性极强。',
    imageUrl: 'https://images.unsplash.com/photo-1516307365426-bea591f05011?w=600&h=400&fit=crop',
    tags: ['十字纹', '手工缝线', '封边'],
  },
  {
    id: 'w004',
    title: '植鞣革名片夹',
    description: '简约设计的植鞣革名片夹，可容纳约20张名片。小巧轻薄，放入口袋毫无负担，是商务人士的理想之选。',
    imageUrl: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=400&fit=crop',
    tags: ['植鞣革', '手工缝线', '封边'],
  },
  {
    id: 'w005',
    title: '编织手环三件套',
    description: '三种不同编织技法组合的手环套装，搭配纯铜搭扣。可单独佩戴或组合搭配，彰显个性。',
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-954f80942964?w=600&h=400&fit=crop',
    tags: ['编织', '植鞣革', '原色'],
  },
  {
    id: 'w006',
    title: '铬鞣革卡包',
    description: '极简风格的铬鞣革卡包，仅4个卡位设计。皮革触感细腻，日常使用的完美单品。',
    imageUrl: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600&h=400&fit=crop',
    tags: ['铬鞣革', '手工缝线', '封边'],
  },
];

export const materialPacks: MaterialPack[] = [
  {
    id: 'm001',
    name: '入门植鞣革短夹材料包',
    price: 128,
    components: [
      '意大利植鞣革裁片 2片',
      '手缝蜡线 1卷',
      '菱斩 1把',
      '缝针 2枚',
      '封边液 1瓶',
      '砂纸 2张',
      '图文教程 1份',
    ],
    tagList: ['植鞣革', '原色', '手工缝线', '封边'],
  },
  {
    id: 'm002',
    name: '进阶编织技法套装',
    price: 268,
    components: [
      '法国小羊皮条 6条',
      '编织辅助工具 1套',
      '手缝蜡线 2卷',
      '纯铜搭扣 3枚',
      '皮革胶水 1支',
      '视频教程 1份',
    ],
    tagList: ['编织', '植鞣革', '手工缝线'],
  },
  {
    id: 'm003',
    name: '十字纹长夹专业包',
    price: 198,
    components: [
      '十字纹牛皮裁片 8片',
      '内里羊皮 2片',
      'YKK拉链 1条',
      '手缝蜡线 3卷',
      '菱斩套装 1套',
      '封边工具 1套',
    ],
    tagList: ['十字纹', '手工缝线', '封边'],
  },
  {
    id: 'm004',
    name: '铬鞣革托特大包材料',
    price: 388,
    components: [
      '法国铬鞣革大片 2张',
      '包带皮革 2条',
      '五金配件 1套',
      '手缝蜡线 3卷',
      '大号菱斩 1把',
      '详细教程 1份',
    ],
    tagList: ['铬鞣革', '编织', '封边', '手工缝线'],
  },
  {
    id: 'm005',
    name: '名片夹简易材料包',
    price: 68,
    components: [
      '植鞣革裁片 2片',
      '手缝蜡线 1卷',
      '迷你菱斩 1把',
      '缝针 2枚',
      '基础教程 1份',
    ],
    tagList: ['植鞣革', '手工缝线', '封边'],
  },
  {
    id: 'm006',
    name: '封边处理工具套装',
    price: 88,
    components: [
      '封边液 2瓶',
      '砂纸板 1块',
      '抛光棒 1根',
      '磨边胶片 3张',
      '使用说明 1份',
    ],
    tagList: ['封边'],
  },
  {
    id: 'm007',
    name: '铬鞣革卡包体验装',
    price: 88,
    components: [
      '铬鞣革裁片 4片',
      '手缝蜡线 1卷',
      '菱斩 1把',
      '缝针 2枚',
      '图文教程 1份',
    ],
    tagList: ['铬鞣革', '手工缝线', '封边'],
  },
  {
    id: 'm008',
    name: '原色植鞣革新手礼包',
    price: 168,
    components: [
      '原色植鞣革练手皮 3块',
      '全套基础工具 1套',
      '手缝蜡线 2卷',
      '多种规格菱斩 1套',
      '新手入门教程 1份',
    ],
    tagList: ['植鞣革', '原色', '手工缝线', '封边'],
  },
  {
    id: 'm009',
    name: '编织手环DIY套装',
    price: 58,
    components: [
      '植鞣革皮条 3条',
      '纯铜搭扣 3枚',
      '辅助胶水 1支',
      '图文教程 1份',
    ],
    tagList: ['编织', '植鞣革', '原色'],
  },
  {
    id: 'm010',
    name: '手工缝线工具大全',
    price: 158,
    components: [
      '进口手缝针 10枚',
      '手缝蜡线 5色各1卷',
      '菱斩 3把',
      '法斩 2把',
      '线剪 1把',
    ],
    tagList: ['手工缝线'],
  },
];

export const orders: Order[] = [
  {
    id: uuidv4(),
    materialPackId: 'm001',
    materialPackName: '入门植鞣革短夹材料包',
    quantity: 1,
    totalPrice: 128,
    status: '已发货',
    customerName: '张三',
    customerPhone: '138****1234',
    createdAt: '2026-06-15T10:30:00Z',
  },
  {
    id: uuidv4(),
    materialPackId: 'm003',
    materialPackName: '十字纹长夹专业包',
    quantity: 2,
    totalPrice: 396,
    status: '已完成',
    customerName: '李四',
    customerPhone: '139****5678',
    createdAt: '2026-06-10T14:20:00Z',
  },
];
