import { Rarity, Card } from './card';

export const CARD_POOL: Omit<Card, 'id' | 'maxHealth' | 'canAttack'>[] = [
  { name: '新兵', cost: 1, attack: 1, health: 2, rarity: Rarity.Common, description: '初入战场的勇敢战士。' },
  { name: '斥候', cost: 1, attack: 2, health: 1, rarity: Rarity.Common, description: '快速移动的侦察兵。' },
  { name: '盾牌兵', cost: 2, attack: 1, health: 4, rarity: Rarity.Common, description: '防御坚固的前线战士。' },
  { name: '弓箭手', cost: 2, attack: 3, health: 2, rarity: Rarity.Common, description: '远程攻击的神射手。' },
  { name: '剑士', cost: 3, attack: 3, health: 3, rarity: Rarity.Common, description: '平衡的近战战士。' },
  { name: '民兵', cost: 1, attack: 1, health: 1, rarity: Rarity.Common, description: '临时征召的平民战士。' },
  { name: '长矛兵', cost: 2, attack: 2, health: 3, rarity: Rarity.Common, description: '擅长对抗骑兵的步兵。' },
  { name: '投石兵', cost: 3, attack: 4, health: 1, rarity: Rarity.Common, description: '高攻低防的支援单位。' },
  { name: '骑士侍从', cost: 3, attack: 2, health: 4, rarity: Rarity.Common, description: '骑士的忠诚随从。' },
  { name: '步兵队长', cost: 4, attack: 3, health: 5, rarity: Rarity.Common, description: '指挥小队的基层军官。' },
  { name: '魔法师学徒', cost: 2, attack: 2, health: 2, rarity: Rarity.Rare, description: '初窥魔法奥秘的学徒。' },
  { name: '治疗牧师', cost: 3, attack: 1, health: 5, rarity: Rarity.Rare, description: '能够治愈队友的神职者。' },
  { name: '游侠', cost: 3, attack: 4, health: 3, rarity: Rarity.Rare, description: '精通箭术与潜行的猎手。' },
  { name: '重装骑士', cost: 5, attack: 4, health: 6, rarity: Rarity.Rare, description: '身披重甲的精锐骑兵。' },
  { name: '元素法师', cost: 4, attack: 5, health: 3, rarity: Rarity.Rare, description: '操控元素之力的法师。' },
  { name: '刺客', cost: 4, attack: 6, health: 2, rarity: Rarity.Rare, description: '一击致命的暗影杀手。' },
  { name: '圣骑士', cost: 5, attack: 3, health: 7, rarity: Rarity.Rare, description: '受圣光庇护的战士。' },
  { name: '火枪手', cost: 4, attack: 5, health: 4, rarity: Rarity.Rare, description: '使用火药武器的射手。' },
  { name: '狼骑兵', cost: 5, attack: 5, health: 5, rarity: Rarity.Rare, description: '骑乘巨狼的蛮族战士。' },
  { name: '战斗法师', cost: 5, attack: 4, health: 4, rarity: Rarity.Rare, description: '兼修武技与魔法的学者。' },
  { name: '巨龙骑士', cost: 7, attack: 6, health: 7, rarity: Rarity.Epic, description: '驾驭巨龙的传奇骑士。' },
  { name: '大魔导师', cost: 6, attack: 7, health: 5, rarity: Rarity.Epic, description: '精通所有魔法学派的大师。' },
  { name: '战争领主', cost: 7, attack: 5, health: 8, rarity: Rarity.Epic, description: '指挥千军万马的统帅。' },
  { name: '暗影刺客', cost: 6, attack: 8, health: 3, rarity: Rarity.Epic, description: '来自暗影的死亡使者。' },
  { name: '神圣牧师', cost: 6, attack: 3, health: 9, rarity: Rarity.Epic, description: '能施展出奇迹的圣者。' },
  { name: '远古守卫', cost: 8, attack: 6, health: 10, rarity: Rarity.Epic, description: '守护古老秘密的石像。' },
  { name: '精灵射手', cost: 7, attack: 7, health: 6, rarity: Rarity.Epic, description: '百步穿杨的精灵神箭手。' },
  { name: '烈焰巨龙', cost: 9, attack: 9, health: 8, rarity: Rarity.Legendary, description: '喷吐烈焰的远古巨龙，战场的毁灭者。' },
  { name: '光明守护神', cost: 8, attack: 7, health: 12, rarity: Rarity.Legendary, description: '降临人间的神明使者，圣光庇佑全军。' },
  { name: '死亡骑士', cost: 10, attack: 10, health: 10, rarity: Rarity.Legendary, description: '曾是正义的英雄，如今统领亡灵大军的巫王。' },
  { name: '时空法师', cost: 9, attack: 8, health: 9, rarity: Rarity.Legendary, description: '操控时间与空间的至高存在，改写命运。' },
  { name: '世界之树化身', cost: 10, attack: 6, health: 15, rarity: Rarity.Legendary, description: '世界之树的化身，拥有无穷生命力。' }
];
