import { v4 as uuidv4 } from 'uuid';
import type {
  User,
  Club,
  Recruitment,
  Application,
  InterviewSlot,
  Portfolio,
  Rating,
} from './types';

export const users: User[] = [
  {
    id: 'admin-1',
    email: 'admin@school.edu',
    name: '系统管理员',
    nickname: 'admin',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'student-1',
    email: 'zhangsan@school.edu',
    name: '张三',
    nickname: 'zhangsan',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'student-2',
    email: 'lisi@school.edu',
    name: '李四',
    nickname: 'lisi',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'student-3',
    email: 'wangwu@school.edu',
    name: '王五',
    nickname: 'wangwu',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
];

export const clubs: Club[] = [
  {
    id: 'club-1',
    name: '编程社',
    description: '致力于培养学生编程能力，开展各类技术分享和竞赛活动',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'club-2',
    name: '摄影社',
    description: '记录校园生活，分享摄影技巧，举办摄影展览',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'club-3',
    name: '音乐社',
    description: '汇聚音乐爱好者，组织音乐会和文艺演出',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'club-4',
    name: '机器人社',
    description: '探索机器人技术，参加各类机器人竞赛',
    createdAt: new Date().toISOString(),
  },
];

export const recruitments: Recruitment[] = [
  {
    id: 'rec-1',
    clubId: 'club-1',
    title: '2024年秋季编程社招新',
    description: '欢迎热爱编程的同学加入！无论你是零基础还是有一定经验，我们都欢迎你。',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rec-2',
    clubId: 'club-2',
    title: '2024年秋季摄影社招新',
    description: '用镜头记录美好瞬间，加入我们一起探索光影的魅力。',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rec-3',
    clubId: 'club-3',
    title: '2024年秋季音乐社招新',
    description: '如果你热爱音乐，无论是声乐、器乐还是创作，都欢迎加入我们！',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rec-4',
    clubId: 'club-4',
    title: '2024年秋季机器人社招新',
    description: '动手实践，创新思维，一起打造属于我们的机器人！',
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published',
    createdAt: new Date().toISOString(),
  },
];

export const applications: Application[] = [
  {
    id: 'app-1',
    recruitmentId: 'rec-1',
    clubId: 'club-1',
    userId: 'student-1',
    studentName: '张三',
    grade: '2023级',
    contact: '13800138001',
    portfolioLinks: ['https://github.com/zhangsan/project1'],
    status: 'accepted',
    interviewStatus: 'completed',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-2',
    recruitmentId: 'rec-1',
    clubId: 'club-1',
    userId: 'student-2',
    studentName: '李四',
    grade: '2024级',
    contact: '13800138002',
    portfolioLinks: ['https://github.com/lisi/awesome-app'],
    status: 'reviewing',
    interviewStatus: 'scheduled',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-3',
    recruitmentId: 'rec-2',
    clubId: 'club-2',
    userId: 'student-1',
    studentName: '张三',
    grade: '2023级',
    contact: '13800138001',
    portfolioLinks: ['https://500px.com/zhangsan/album1'],
    status: 'accepted',
    interviewStatus: 'completed',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-4',
    recruitmentId: 'rec-2',
    clubId: 'club-2',
    userId: 'student-3',
    studentName: '王五',
    grade: '2024级',
    contact: '13800138003',
    portfolioLinks: ['https://unsplash.com/wangwu/collection'],
    status: 'pending',
    interviewStatus: 'none',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-5',
    recruitmentId: 'rec-3',
    clubId: 'club-3',
    userId: 'student-2',
    studentName: '李四',
    grade: '2024级',
    contact: '13800138002',
    portfolioLinks: ['https://bilibili.com/video/BV123456'],
    status: 'reviewing',
    interviewStatus: 'none',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-6',
    recruitmentId: 'rec-4',
    clubId: 'club-4',
    userId: 'student-3',
    studentName: '王五',
    grade: '2024级',
    contact: '13800138003',
    portfolioLinks: ['https://github.com/wangwu/robot-arm'],
    status: 'accepted',
    interviewStatus: 'completed',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const interviewSlots: InterviewSlot[] = [
  {
    id: 'slot-1',
    recruitmentId: 'rec-1',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '15:00',
    maxCapacity: 5,
    currentCount: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slot-2',
    recruitmentId: 'rec-1',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '15:00',
    endTime: '16:00',
    maxCapacity: 5,
    currentCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slot-3',
    recruitmentId: 'rec-1',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '16:00',
    maxCapacity: 10,
    currentCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slot-4',
    recruitmentId: 'rec-2',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '10:00',
    endTime: '12:00',
    maxCapacity: 8,
    currentCount: 0,
    createdAt: new Date().toISOString(),
  },
];

export const portfolios: Portfolio[] = [
  {
    id: 'port-1',
    applicationId: 'app-1',
    userId: 'student-1',
    authorNickname: 'zhangsan',
    title: '校园导航系统',
    link: 'https://github.com/zhangsan/project1',
    description: '一个基于React的校园导航Web应用，支持室内室外无缝导航，集成了实时人流量数据和智能路径规划功能。使用了最新的WebGL技术实现3D地图渲染。',
    status: 'approved',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'port-2',
    applicationId: 'app-3',
    userId: 'student-1',
    authorNickname: 'zhangsan',
    title: '校园四季摄影集',
    link: 'https://500px.com/zhangsan/album1',
    description: '记录了校园一年四季的美丽风光，从春天的樱花到冬天的雪景，用镜头捕捉每一个动人瞬间。包含50张精选照片，全部使用专业相机拍摄并后期精修。',
    status: 'approved',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'port-3',
    applicationId: 'app-6',
    userId: 'student-3',
    authorNickname: 'wangwu',
    title: '智能机械臂控制系统',
    link: 'https://github.com/wangwu/robot-arm',
    description: '基于Arduino和Python开发的6自由度机械臂控制系统，支持手势控制和路径规划算法。在省级机器人竞赛中获得一等奖。',
    status: 'approved',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'port-4',
    applicationId: 'app-2',
    userId: 'student-2',
    authorNickname: 'lisi',
    title: '校园二手交易平台',
    link: 'https://github.com/lisi/awesome-app',
    description: '一个专注于校园场景的二手交易小程序，支持实名认证、信用评价、智能推荐等功能。目前已有超过1000名注册用户。',
    status: 'approved',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'port-5',
    applicationId: 'app-5',
    userId: 'student-2',
    authorNickname: 'lisi',
    title: '原创音乐专辑《青春记忆》',
    link: 'https://bilibili.com/video/BV123456',
    description: '一张完全由自己作词作曲编曲的原创专辑，包含10首歌曲，风格涵盖流行、民谣和电子音乐。在网易云音乐播放量超过10万。',
    status: 'approved',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'port-6',
    applicationId: 'app-4',
    userId: 'student-3',
    authorNickname: 'wangwu',
    title: '城市夜景系列摄影',
    link: 'https://unsplash.com/wangwu/collection',
    description: '一组城市夜景摄影作品，探索光与影的艺术表达。使用长时间曝光技术，展现城市夜晚独特的魅力。',
    status: 'pending',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const ratings: Rating[] = [
  {
    id: 'rate-1',
    portfolioId: 'port-1',
    userId: 'student-2',
    raterNickname: 'lisi',
    score: 5,
    comment: '界面设计很漂亮，功能也很实用，特别是3D导航功能太棒了！',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-2',
    portfolioId: 'port-1',
    userId: 'student-3',
    raterNickname: 'wangwu',
    score: 4,
    comment: '技术很强大，但如果能增加更多建筑的室内地图就更好了。',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-3',
    portfolioId: 'port-2',
    userId: 'student-3',
    raterNickname: 'wangwu',
    score: 5,
    comment: '照片太美了！构图和光线都很专业，看完想立刻去拍照片。',
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-4',
    portfolioId: 'port-2',
    userId: 'student-2',
    raterNickname: 'lisi',
    score: 4,
    comment: '很有艺术感，春天樱花那张特别惊艳。',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-5',
    portfolioId: 'port-3',
    userId: 'student-1',
    raterNickname: 'zhangsan',
    score: 5,
    comment: '太厉害了！机械臂的运动非常流畅，手势识别也很准确。',
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-6',
    portfolioId: 'port-3',
    userId: 'student-2',
    raterNickname: 'lisi',
    score: 5,
    comment: '获奖实至名归，希望能看到更多进阶功能！',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-7',
    portfolioId: 'port-4',
    userId: 'student-1',
    raterNickname: 'zhangsan',
    score: 4,
    comment: '功能很完整，用户体验也不错，建议增加即时通讯功能。',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-8',
    portfolioId: 'port-4',
    userId: 'student-3',
    raterNickname: 'wangwu',
    score: 4,
    comment: 'UI设计简洁大方，交易流程很顺畅。',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-9',
    portfolioId: 'port-5',
    userId: 'student-1',
    raterNickname: 'zhangsan',
    score: 5,
    comment: '太有才了！每首歌都很好听，循环播放中...',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rate-10',
    portfolioId: 'port-5',
    userId: 'student-3',
    raterNickname: 'wangwu',
    score: 4,
    comment: '创作能力很强，编曲可以再丰富一些。',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export function generateId(): string {
  return uuidv4();
}
