import type { ComponentConfig, ComponentCategory } from '@/types';

const components: ComponentConfig[] = [
  // ============ 墙体类 ============
  {
    id: 'wall-basic',
    name: '基本墙体',
    category: 'walls',
    geometry: { type: 'box', params: [3, 2.5, 0.15] },
    material: { color: '#e2e8f0', roughness: 0.85 },
    thumbnailColor: '#cbd5e1',
    gridSize: [3, 2.5, 0.15],
    shape2D: 'rect',
    lineHeight: 0.15,
  },
  {
    id: 'wall-short',
    name: '短墙体',
    category: 'walls',
    geometry: { type: 'box', params: [1.5, 2.5, 0.15] },
    material: { color: '#f1f5f9', roughness: 0.85 },
    thumbnailColor: '#94a3b8',
    gridSize: [1.5, 2.5, 0.15],
    shape2D: 'rect',
    lineHeight: 0.15,
  },
  {
    id: 'wall-tall',
    name: '高隔墙',
    category: 'walls',
    geometry: { type: 'box', params: [2, 3.2, 0.12] },
    material: { color: '#f8fafc', roughness: 0.8 },
    thumbnailColor: '#64748b',
    gridSize: [2, 3.2, 0.12],
    shape2D: 'rect',
    lineHeight: 0.12,
  },
  {
    id: 'wall-curved',
    name: '弧形柱',
    category: 'walls',
    geometry: { type: 'cylinder', params: [0.3, 0.3, 2.8, 16] },
    material: { color: '#cbd5e1', roughness: 0.7 },
    thumbnailColor: '#475569',
    gridSize: [0.6, 2.8, 0.6],
    shape2D: 'circle',
  },
  {
    id: 'wall-half',
    name: '半高隔断',
    category: 'walls',
    geometry: { type: 'box', params: [2, 1.2, 0.1] },
    material: { color: '#e0e7ff', roughness: 0.8 },
    thumbnailColor: '#a5b4fc',
    gridSize: [2, 1.2, 0.1],
    shape2D: 'rect',
    lineHeight: 0.1,
  },
  {
    id: 'wall-glass',
    name: '玻璃墙',
    category: 'walls',
    geometry: { type: 'box', params: [2.5, 2.2, 0.04] },
    material: { color: '#bae6fd', roughness: 0.05, metalness: 0.2, opacity: 0.4 },
    thumbnailColor: '#7dd3fc',
    gridSize: [2.5, 2.2, 0.04],
    shape2D: 'rect',
    lineHeight: 0.04,
  },

  // ============ 家具类 ============
  {
    id: 'sofa-3seat',
    name: '三人沙发',
    category: 'furniture',
    geometry: { type: 'box', params: [2.2, 0.5, 0.9] },
    material: { color: '#64748b', roughness: 0.9 },
    thumbnailColor: '#64748b',
    gridSize: [2.2, 0.5, 0.9],
    shape2D: 'rect',
  },
  {
    id: 'sofa-2seat',
    name: '双人沙发',
    category: 'furniture',
    geometry: { type: 'box', params: [1.6, 0.5, 0.85] },
    material: { color: '#475569', roughness: 0.9 },
    thumbnailColor: '#334155',
    gridSize: [1.6, 0.5, 0.85],
    shape2D: 'rect',
  },
  {
    id: 'table-dining',
    name: '餐桌',
    category: 'furniture',
    geometry: { type: 'box', params: [1.6, 0.05, 0.9] },
    material: { color: '#78350f', roughness: 0.6, metalness: 0.05 },
    thumbnailColor: '#92400e',
    gridSize: [1.6, 0.75, 0.9],
    shape2D: 'rect',
  },
  {
    id: 'table-coffee',
    name: '茶几',
    category: 'furniture',
    geometry: { type: 'box', params: [1.1, 0.04, 0.6] },
    material: { color: '#1f2937', roughness: 0.3, metalness: 0.1 },
    thumbnailColor: '#374151',
    gridSize: [1.1, 0.45, 0.6],
    shape2D: 'rect',
  },
  {
    id: 'table-desk',
    name: '办公桌',
    category: 'furniture',
    geometry: { type: 'box', params: [1.4, 0.05, 0.7] },
    material: { color: '#7c2d12', roughness: 0.5 },
    thumbnailColor: '#b45309',
    gridSize: [1.4, 0.75, 0.7],
    shape2D: 'rect',
  },
  {
    id: 'chair-office',
    name: '办公椅',
    category: 'furniture',
    geometry: { type: 'box', params: [0.55, 0.04, 0.55] },
    material: { color: '#1e293b', roughness: 0.8 },
    thumbnailColor: '#0f172a',
    gridSize: [0.55, 1.1, 0.55],
    shape2D: 'rect',
  },
  {
    id: 'chair-dining',
    name: '餐椅',
    category: 'furniture',
    geometry: { type: 'box', params: [0.45, 0.04, 0.45] },
    material: { color: '#78350f', roughness: 0.7 },
    thumbnailColor: '#d97706',
    gridSize: [0.45, 0.9, 0.45],
    shape2D: 'rect',
  },
  {
    id: 'bed-double',
    name: '双人床',
    category: 'furniture',
    geometry: { type: 'box', params: [1.8, 0.35, 2.0] },
    material: { color: '#e5e7eb', roughness: 0.95 },
    thumbnailColor: '#f3f4f6',
    gridSize: [1.8, 0.5, 2.0],
    shape2D: 'rect',
  },
  {
    id: 'cabinet-wardrobe',
    name: '衣柜',
    category: 'furniture',
    geometry: { type: 'box', params: [1.6, 2.2, 0.55] },
    material: { color: '#78350f', roughness: 0.65 },
    thumbnailColor: '#a16207',
    gridSize: [1.6, 2.2, 0.55],
    shape2D: 'rect',
  },
  {
    id: 'shelf-book',
    name: '书架',
    category: 'furniture',
    geometry: { type: 'box', params: [0.9, 1.8, 0.3] },
    material: { color: '#44403c', roughness: 0.7 },
    thumbnailColor: '#57534e',
    gridSize: [0.9, 1.8, 0.3],
    shape2D: 'rect',
  },

  // ============ 植物类 ============
  {
    id: 'plant-large',
    name: '大型盆栽',
    category: 'plants',
    geometry: { type: 'cylinder', params: [0.25, 0.3, 0.5, 16] },
    material: { color: '#854d0e', roughness: 0.9 },
    thumbnailColor: '#16a34a',
    gridSize: [0.6, 1.5, 0.6],
    shape2D: 'circle',
  },
  {
    id: 'plant-medium',
    name: '中型植物',
    category: 'plants',
    geometry: { type: 'cylinder', params: [0.18, 0.2, 0.35, 12] },
    material: { color: '#a16207', roughness: 0.9 },
    thumbnailColor: '#22c55e',
    gridSize: [0.4, 1.0, 0.4],
    shape2D: 'circle',
  },
  {
    id: 'plant-small',
    name: '桌面盆栽',
    category: 'plants',
    geometry: { type: 'cylinder', params: [0.1, 0.12, 0.18, 10] },
    material: { color: '#92400e', roughness: 0.85 },
    thumbnailColor: '#4ade80',
    gridSize: [0.22, 0.4, 0.22],
    shape2D: 'circle',
  },
  {
    id: 'plant-tree',
    name: '小树装饰',
    category: 'plants',
    geometry: { type: 'cone', params: [0.4, 1.2, 16] },
    material: { color: '#15803d', roughness: 0.95 },
    thumbnailColor: '#166534',
    gridSize: [0.8, 1.8, 0.8],
    shape2D: 'circle',
  },

  // ============ 装饰类 ============
  {
    id: 'rug-square',
    name: '方形地毯',
    category: 'decorations',
    geometry: { type: 'box', params: [2.5, 0.02, 1.8] },
    material: { color: '#7c3aed', roughness: 1.0 },
    thumbnailColor: '#8b5cf6',
    gridSize: [2.5, 0.02, 1.8],
    shape2D: 'rect',
  },
  {
    id: 'rug-rect',
    name: '长形地毯',
    category: 'decorations',
    geometry: { type: 'box', params: [3.0, 0.02, 2.0] },
    material: { color: '#be185d', roughness: 1.0 },
    thumbnailColor: '#ec4899',
    gridSize: [3.0, 0.02, 2.0],
    shape2D: 'rect',
  },
  {
    id: 'lamp-floor',
    name: '落地灯',
    category: 'decorations',
    geometry: { type: 'cylinder', params: [0.08, 0.08, 1.6, 8] },
    material: { color: '#1f2937', roughness: 0.4, metalness: 0.6 },
    thumbnailColor: '#fde68a',
    gridSize: [0.35, 1.8, 0.35],
    shape2D: 'circle',
  },
  {
    id: 'lamp-table',
    name: '台灯',
    category: 'decorations',
    geometry: { type: 'cylinder', params: [0.12, 0.05, 0.08, 10] },
    material: { color: '#374151', roughness: 0.5, metalness: 0.4 },
    thumbnailColor: '#fbbf24',
    gridSize: [0.24, 0.45, 0.24],
    shape2D: 'circle',
  },
  {
    id: 'painting',
    name: '挂画',
    category: 'decorations',
    geometry: { type: 'box', params: [0.9, 0.6, 0.03] },
    material: { color: '#e0f2fe', roughness: 0.5 },
    thumbnailColor: '#0ea5e9',
    gridSize: [0.9, 0.6, 0.03],
    shape2D: 'rect',
    lineHeight: 0.03,
  },
  {
    id: 'tv-screen',
    name: '电视屏幕',
    category: 'decorations',
    geometry: { type: 'box', params: [1.5, 0.9, 0.05] },
    material: { color: '#020617', roughness: 0.2, metalness: 0.1 },
    thumbnailColor: '#1e293b',
    gridSize: [1.5, 0.9, 0.05],
    shape2D: 'rect',
    lineHeight: 0.05,
  },
  {
    id: 'mirror',
    name: '装饰镜',
    category: 'decorations',
    geometry: { type: 'box', params: [0.7, 1.2, 0.03] },
    material: { color: '#e0f2fe', roughness: 0.05, metalness: 0.7 },
    thumbnailColor: '#67e8f9',
    gridSize: [0.7, 1.2, 0.03],
    shape2D: 'rect',
    lineHeight: 0.03,
  },
  {
    id: 'shelf-decor',
    name: '置物架',
    category: 'decorations',
    geometry: { type: 'box', params: [0.8, 0.03, 0.25] },
    material: { color: '#78716c', roughness: 0.6 },
    thumbnailColor: '#a8a29e',
    gridSize: [0.8, 1.5, 0.25],
    shape2D: 'rect',
  },
];

const categoryLabels: Record<ComponentCategory, string> = {
  walls: '墙体',
  furniture: '家具',
  plants: '植物',
  decorations: '装饰',
};

export function getComponentById(id: string): ComponentConfig | undefined {
  return components.find((c) => c.id === id);
}

export function getComponentsByCategory(category: ComponentCategory): ComponentConfig[] {
  return components.filter((c) => c.category === category);
}

export function getAllCategories(): { key: ComponentCategory; label: string }[] {
  return Object.keys(categoryLabels).map((k) => ({
    key: k as ComponentCategory,
    label: categoryLabels[k as ComponentCategory],
  }));
}

export function getAllComponents(): ComponentConfig[] {
  return components;
}
