import { saveAs } from 'file-saver';
import type { OverflowElement, BreakpointResult } from './analyzer';

export interface ExportJsonData {
  exportedAt: string;
  breakpoints: Record<string, BreakpointResult>;
  config: {
    fontScale: number;
    lineHeight: number;
    padding: number;
  };
  summary: {
    totalOverflowElements: number;
    affectedBreakpoints: number[];
    mostSevereOverflow: {
      breakpoint: number;
      element: OverflowElement | null;
    };
  };
}

export async function exportToPng(
  iframe: HTMLIFrameElement,
  overflowElements: OverflowElement[],
  breakpoint: number
): Promise<void> {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Canvas context not available');

  const width = 1920;
  const height = 1080;
  canvas.width = width;
  canvas.height = height;

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  ctx.fillStyle = '#2a2a3a';
  ctx.fillRect(0, 0, width, 80);
  ctx.fillStyle = '#e0e0e0';
  ctx.font = 'bold 28px sans-serif';
  ctx.fillText(`Layout Diagnostic Report - ${breakpoint}px`, 40, 50);

  const iframeDoc = iframe.contentDocument;
  if (iframeDoc) {
    const scale = Math.min((width - 80) / breakpoint, (height - 200) / 800);
    const startX = 40;
    const startY = 110;

    ctx.strokeStyle = '#4a6fa5';
    ctx.lineWidth = 2;
    ctx.strokeRect(startX - 4, startY - 4, breakpoint * scale + 8, 800 * scale + 8);

    ctx.fillStyle = '#f5f5f5';
    ctx.fillRect(startX, startY, breakpoint * scale, 800 * scale);

    ctx.fillStyle = '#1a1a2a';
    ctx.font = '16px sans-serif';
    ctx.fillText('Viewport Preview', startX, startY + 25);

    overflowElements.forEach((elem, index) => {
      const yOffset = 150 + index * 100;
      const isHorizontal = elem.overflowType.includes('horizontal');
      const isVertical = elem.overflowType.includes('vertical');

      ctx.fillStyle = 'rgba(239, 68, 68, 0.25)';
      ctx.fillRect(startX, yOffset, width - 80, 80);

      ctx.strokeStyle = '#ef4444';
      ctx.lineWidth = 2;
      ctx.strokeRect(startX, yOffset, width - 80, 80);

      ctx.fillStyle = '#1a1a2a';
      ctx.font = 'bold 16px sans-serif';
      ctx.fillText(elem.selector, startX + 15, yOffset + 28);

      ctx.fillStyle = '#666';
      ctx.font = '13px sans-serif';
      ctx.fillText(
        `尺寸: ${elem.actualWidth}px × ${elem.actualHeight}px | 父容器: ${elem.parentWidth}px × ${elem.parentHeight}px`,
        startX + 15,
        yOffset + 50
      );

      let overflowText = '';
      if (isHorizontal) overflowText += `水平溢出: ${elem.overflowX}px  `;
      if (isVertical) overflowText += `垂直溢出: ${elem.overflowY}px`;
      ctx.fillStyle = '#ef4444';
      ctx.font = 'bold 14px sans-serif';
      ctx.fillText(overflowText, startX + 15, yOffset + 70);

      ctx.fillStyle = '#f97316';
      ctx.font = 'bold 32px sans-serif';
      ctx.fillText(`${elem.overflowX + elem.overflowY}px`, width - 120, yOffset + 52);
    });
  }

  ctx.fillStyle = '#f0f0f0';
  ctx.fillRect(0, height - 50, width, 50);
  ctx.fillStyle = '#666';
  ctx.font = '14px sans-serif';
  ctx.fillText(`Generated by Layout Diagnostic Tool | ${new Date().toLocaleString()}`, 40, height - 20);

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        saveAs(blob, `layout-diagnostic-${breakpoint}px.png`);
        resolve();
      } else {
        reject(new Error('Failed to generate PNG blob'));
      }
    }, 'image/png');
  });
}

export function exportToJson(
  breakpointsData: Record<string, BreakpointResult>,
  config: { fontScale: number; lineHeight: number; padding: number }
): void {
  let totalElements = 0;
  const affectedBps: number[] = [];
  let mostSevere: { breakpoint: number; element: OverflowElement | null } = {
    breakpoint: 0,
    element: null
  };

  Object.entries(breakpointsData).forEach(([key, bp]) => {
    totalElements += bp.totalOverflow;
    if (bp.totalOverflow > 0) {
      affectedBps.push(bp.breakpoint);
    }
    bp.overflowElements.forEach((elem) => {
      const maxOverflow = Math.max(elem.overflowX, elem.overflowY);
      const currentMax = mostSevere.element
        ? Math.max(mostSevere.element.overflowX, mostSevere.element.overflowY)
        : 0;
      if (maxOverflow > currentMax) {
        mostSevere = { breakpoint: bp.breakpoint, element: elem };
      }
    });
  });

  const exportData: ExportJsonData = {
    exportedAt: new Date().toISOString(),
    breakpoints: breakpointsData,
    config,
    summary: {
      totalOverflowElements: totalElements,
      affectedBreakpoints: affectedBps.sort((a, b) => a - b),
      mostSevereOverflow: mostSevere
    }
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: 'application/json'
  });
  saveAs(blob, 'layout-diagnostic-report.json');
}
