import type { ComponentRegistry, ComponentType } from '@/types/componentTypes';

export const componentRegistries: Record<ComponentType, ComponentRegistry> = {
  button: {
    type: 'button',
    name: '按钮',
    icon: '🔘',
    defaultProps: {
      width: 120,
      height: 40,
      label: '按钮',
      variant: 'primary',
      disabled: false,
      primaryColor: '#ffd700',
      backgroundColor: '#2a2a2a',
      fontSize: 14,
      borderRadius: 6,
      paddingX: 16,
      paddingY: 8,
    },
    fieldConfigs: [
      { key: 'label', label: '标签文本', type: 'text' },
      {
        key: 'variant',
        label: '样式变体',
        type: 'select',
        options: ['primary', 'secondary', 'outline', 'ghost'],
      },
      { key: 'disabled', label: '禁用状态', type: 'boolean' },
      { key: 'primaryColor', label: '主色调', type: 'color' },
      { key: 'backgroundColor', label: '背景色', type: 'color' },
      { key: 'fontSize', label: '字号', type: 'range', min: 10, max: 24, step: 1 },
      { key: 'borderRadius', label: '圆角半径', type: 'range', min: 0, max: 24, step: 1 },
      { key: 'paddingX', label: '水平内边距', type: 'range', min: 4, max: 32, step: 2 },
      { key: 'paddingY', label: '垂直内边距', type: 'range', min: 2, max: 24, step: 2 },
      { key: 'width', label: '宽度', type: 'number', min: 60, max: 400 },
      { key: 'height', label: '高度', type: 'number', min: 24, max: 120 },
    ],
  },
  input: {
    type: 'input',
    name: '输入框',
    icon: '📝',
    defaultProps: {
      width: 240,
      height: 40,
      placeholder: '请输入内容',
      value: '',
      disabled: false,
      focused: false,
      primaryColor: '#ffd700',
      backgroundColor: '#2a2a2a',
      borderRadius: 6,
      fontSize: 14,
      paddingX: 12,
      paddingY: 8,
    },
    fieldConfigs: [
      { key: 'placeholder', label: '占位符', type: 'text' },
      { key: 'value', label: '当前值', type: 'text' },
      { key: 'disabled', label: '禁用状态', type: 'boolean' },
      { key: 'focused', label: '聚焦状态', type: 'boolean' },
      { key: 'primaryColor', label: '主色调', type: 'color' },
      { key: 'backgroundColor', label: '背景色', type: 'color' },
      { key: 'borderRadius', label: '圆角半径', type: 'range', min: 0, max: 24, step: 1 },
      { key: 'fontSize', label: '字号', type: 'range', min: 10, max: 24, step: 1 },
      { key: 'paddingX', label: '水平内边距', type: 'range', min: 4, max: 32, step: 2 },
      { key: 'paddingY', label: '垂直内边距', type: 'range', min: 2, max: 24, step: 2 },
      { key: 'width', label: '宽度', type: 'number', min: 100, max: 600 },
      { key: 'height', label: '高度', type: 'number', min: 24, max: 120 },
    ],
  },
  card: {
    type: 'card',
    name: '卡片',
    icon: '🃏',
    defaultProps: {
      width: 280,
      height: 320,
      title: '卡片标题',
      description: '这是卡片的描述文本，可以包含一些详细信息。',
      imageUrl: '',
      elevation: 2,
      primaryColor: '#ffd700',
      backgroundColor: '#2a2a2a',
      borderRadius: 8,
    },
    fieldConfigs: [
      { key: 'title', label: '卡片标题', type: 'text' },
      { key: 'description', label: '描述文本', type: 'textarea' },
      { key: 'imageUrl', label: '图片URL', type: 'text' },
      { key: 'elevation', label: '阴影层级', type: 'range', min: 0, max: 5, step: 1 },
      { key: 'primaryColor', label: '主色调', type: 'color' },
      { key: 'backgroundColor', label: '背景色', type: 'color' },
      { key: 'borderRadius', label: '圆角半径', type: 'range', min: 0, max: 32, step: 1 },
      { key: 'width', label: '宽度', type: 'number', min: 150, max: 500 },
      { key: 'height', label: '高度', type: 'number', min: 150, max: 600 },
    ],
  },
  modal: {
    type: 'modal',
    name: '模态框',
    icon: '🪟',
    defaultProps: {
      width: 400,
      height: 300,
      title: '模态框标题',
      content: '这是模态框的内容区域。',
      showCloseButton: true,
      primaryColor: '#ffd700',
      backgroundColor: '#2a2a2a',
      borderRadius: 8,
      overlayOpacity: 0.5,
    },
    fieldConfigs: [
      { key: 'title', label: '模态框标题', type: 'text' },
      { key: 'content', label: '内容文本', type: 'textarea' },
      { key: 'showCloseButton', label: '显示关闭按钮', type: 'boolean' },
      { key: 'primaryColor', label: '主色调', type: 'color' },
      { key: 'backgroundColor', label: '背景色', type: 'color' },
      { key: 'borderRadius', label: '圆角半径', type: 'range', min: 0, max: 32, step: 1 },
      { key: 'overlayOpacity', label: '遮罩透明度', type: 'range', min: 0, max: 1, step: 0.1 },
      { key: 'width', label: '宽度', type: 'number', min: 200, max: 700 },
      { key: 'height', label: '高度', type: 'number', min: 150, max: 600 },
    ],
  },
  tabs: {
    type: 'tabs',
    name: '标签页',
    icon: '📑',
    defaultProps: {
      width: 360,
      height: 200,
      tabs: ['标签一', '标签二', '标签三'],
      activeTab: 0,
      primaryColor: '#ffd700',
      backgroundColor: '#2a2a2a',
      borderRadius: 6,
    },
    fieldConfigs: [
      { key: 'tabs', label: '标签名称(逗号分隔)', type: 'array' },
      { key: 'activeTab', label: '激活标签索引', type: 'number', min: 0, max: 9 },
      { key: 'primaryColor', label: '主色调', type: 'color' },
      { key: 'backgroundColor', label: '背景色', type: 'color' },
      { key: 'borderRadius', label: '圆角半径', type: 'range', min: 0, max: 24, step: 1 },
      { key: 'width', label: '宽度', type: 'number', min: 200, max: 700 },
      { key: 'height', label: '高度', type: 'number', min: 100, max: 500 },
    ],
  },
};

export const componentTypeList: ComponentType[] = ['button', 'input', 'card', 'modal', 'tabs'];
