import { Hero, Enemy } from './types';

export const HERO_DATA: Omit<Hero, 'x' | 'y'>[] = [
  {
    id: 'warrior',
    name: '战士',
    heroClass: 'warrior',
    hp: 120,
    maxHp: 120,
    atk: 28,
    def: 15,
    skill: {
      name: '猛力斩击',
      damage: 45,
      multiplier: 2.0,
      description: '全力挥砍，造成双倍伤害',
      icon: 'sword',
    },
    cooldown: 0,
    maxCooldown: 3,
    isAlive: true,
    unlockCost: 0,
    unlocked: true,
    skinVariant: 0,
  },
  {
    id: 'mage',
    name: '法师',
    heroClass: 'mage',
    hp: 80,
    maxHp: 80,
    atk: 35,
    def: 6,
    skill: {
      name: '烈焰风暴',
      damage: 60,
      multiplier: 2.5,
      description: '召唤火焰风暴，焚烧一切',
      icon: 'staff',
    },
    cooldown: 0,
    maxCooldown: 4,
    isAlive: true,
    unlockCost: 0,
    unlocked: true,
    skinVariant: 0,
  },
  {
    id: 'archer',
    name: '弓箭手',
    heroClass: 'archer',
    hp: 90,
    maxHp: 90,
    atk: 32,
    def: 8,
    skill: {
      name: '穿云箭',
      damage: 50,
      multiplier: 2.2,
      description: '一箭穿云，精准制敌',
      icon: 'bow',
    },
    cooldown: 0,
    maxCooldown: 3,
    isAlive: true,
    unlockCost: 0,
    unlocked: true,
    skinVariant: 0,
  },
  {
    id: 'assassin',
    name: '刺客',
    heroClass: 'assassin',
    hp: 75,
    maxHp: 75,
    atk: 38,
    def: 5,
    skill: {
      name: '暗影突袭',
      damage: 65,
      multiplier: 2.8,
      description: '从暗影中突袭，致命一击',
      icon: 'dagger',
    },
    cooldown: 0,
    maxCooldown: 4,
    isAlive: true,
    unlockCost: 0,
    unlocked: true,
    skinVariant: 0,
  },
  {
    id: 'paladin',
    name: '圣骑士',
    heroClass: 'paladin',
    hp: 130,
    maxHp: 130,
    atk: 22,
    def: 20,
    skill: {
      name: '神圣打击',
      damage: 40,
      multiplier: 1.8,
      description: '以神圣之力打击敌人',
      icon: 'shield',
    },
    cooldown: 0,
    maxCooldown: 3,
    isAlive: true,
    unlockCost: 100,
    unlocked: false,
    skinVariant: 0,
  },
  {
    id: 'warlock',
    name: '术士',
    heroClass: 'warlock',
    hp: 85,
    maxHp: 85,
    atk: 33,
    def: 7,
    skill: {
      name: '灵魂汲取',
      damage: 55,
      multiplier: 2.3,
      description: '汲取敌人灵魂，恢复自身',
      icon: 'skull',
    },
    cooldown: 0,
    maxCooldown: 4,
    isAlive: true,
    unlockCost: 150,
    unlocked: false,
    skinVariant: 0,
  },
];

const ENEMY_WAVES: Omit<Enemy, 'x' | 'y'>[][] = [
  [
    { id: 'e1', name: '哥布林斥候', hp: 50, maxHp: 50, atk: 12, def: 4, isAlive: true },
    { id: 'e2', name: '哥布林战士', hp: 65, maxHp: 65, atk: 15, def: 6, isAlive: true },
    { id: 'e3', name: '哥布林弓手', hp: 40, maxHp: 40, atk: 18, def: 3, isAlive: true },
  ],
  [
    { id: 'e1', name: '骷髅兵', hp: 70, maxHp: 70, atk: 18, def: 8, isAlive: true },
    { id: 'e2', name: '暗影狼', hp: 55, maxHp: 55, atk: 22, def: 5, isAlive: true },
    { id: 'e3', name: '食尸鬼', hp: 80, maxHp: 80, atk: 16, def: 10, isAlive: true },
  ],
  [
    { id: 'e1', name: '暗黑骑士', hp: 100, maxHp: 100, atk: 25, def: 12, isAlive: true },
    { id: 'e2', name: '死灵法师', hp: 75, maxHp: 75, atk: 30, def: 6, isAlive: true },
    { id: 'e3', name: '炎魔', hp: 120, maxHp: 120, atk: 28, def: 10, isAlive: true },
  ],
];

export function getEnemyWave(waveIndex: number): Omit<Enemy, 'x' | 'y'>[] {
  const idx = waveIndex % ENEMY_WAVES.length;
  const wave = ENEMY_WAVES[idx];
  return wave.map((e, i) => ({
    ...e,
    id: `e${i}_${Date.now()}`,
    hp: e.hp + waveIndex * 10,
    maxHp: e.maxHp + waveIndex * 10,
    atk: e.atk + waveIndex * 3,
    def: e.def + waveIndex * 2,
  }));
}
