export interface Template {
  id: string;
  name: string;
  category: string;
  thumbnail: string;
  data: {
    objects: any[];
    background: string;
  };
}

export const templates: Template[] = [
  {
    id: 'business',
    name: '商务海报',
    category: '商务',
    thumbnail: '',
    data: {
      background: '#1e3a5f',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 800,
          height: 200,
          fill: '#4a90d9',
          selectable: false,
          evented: false,
        },
        {
          type: 'text',
          left: 60,
          top: 80,
          text: '企业宣传海报',
          fontFamily: 'Arial',
          fontSize: 48,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 60,
          top: 150,
          text: 'BUSINESS POSTER',
          fontFamily: 'Arial',
          fontSize: 20,
          fill: '#e2e8f0',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 60,
          top: 280,
          text: '创新驱动未来',
          fontFamily: 'Georgia',
          fontSize: 36,
          fill: '#ffffff',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 60,
          top: 340,
          text: '专业 · 高效 · 值得信赖',
          fontFamily: 'Arial',
          fontSize: 24,
          fill: '#cbd5e1',
          textAlign: 'left',
        },
        {
          type: 'rect',
          left: 60,
          top: 400,
          width: 120,
          height: 4,
          fill: '#4a90d9',
        },
        {
          type: 'text',
          left: 60,
          top: 450,
          text: '关于我们',
          fontFamily: 'Arial',
          fontSize: 28,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 60,
          top: 500,
          text: '我们致力于为客户提供最优质的服务\n用专业和热情打造每一个项目',
          fontFamily: 'Arial',
          fontSize: 18,
          fill: '#94a3b8',
          textAlign: 'left',
          lineHeight: 1.8,
        },
        {
          type: 'circle',
          left: 650,
          top: 300,
          radius: 80,
          fill: '#4a90d9',
          opacity: 0.3,
        },
        {
          type: 'circle',
          left: 700,
          top: 250,
          radius: 50,
          fill: '#60a5fa',
          opacity: 0.5,
        },
      ],
    },
  },
  {
    id: 'birthday',
    name: '生日贺卡',
    category: '生日',
    thumbnail: '',
    data: {
      background: '#fef3c7',
      objects: [
        {
          type: 'circle',
          left: 400,
          top: 150,
          radius: 100,
          fill: '#f59e0b',
          opacity: 0.2,
        },
        {
          type: 'circle',
          left: 400,
          top: 150,
          radius: 70,
          fill: '#f59e0b',
          opacity: 0.4,
        },
        {
          type: 'text',
          left: 400,
          top: 130,
          text: '🎉',
          fontFamily: 'Arial',
          fontSize: 80,
          fill: '#f59e0b',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 280,
          text: '生日快乐',
          fontFamily: 'Georgia',
          fontSize: 56,
          fontWeight: 'bold',
          fill: '#dc2626',
          textAlign: 'center',
          originX: 'center',
          fontStyle: 'italic',
        },
        {
          type: 'text',
          left: 400,
          top: 360,
          text: 'HAPPY BIRTHDAY',
          fontFamily: 'Impact',
          fontSize: 32,
          fill: '#ea580c',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 450,
          text: '愿你今天充满欢笑与快乐\n愿所有的美好都围绕着你',
          fontFamily: 'Georgia',
          fontSize: 24,
          fill: '#92400e',
          textAlign: 'center',
          originX: 'center',
          lineHeight: 1.8,
          fontStyle: 'italic',
        },
        {
          type: 'rect',
          left: 100,
          top: 600,
          width: 600,
          height: 100,
          fill: '#fbbf24',
          rx: 20,
          ry: 20,
          opacity: 0.3,
        },
        {
          type: 'text',
          left: 400,
          top: 630,
          text: '🎂  🎈  🎁  🌟  🎊',
          fontFamily: 'Arial',
          fontSize: 36,
          fill: '#dc2626',
          textAlign: 'center',
          originX: 'center',
        },
      ],
    },
  },
  {
    id: 'party',
    name: '派对邀请',
    category: '派对',
    thumbnail: '',
    data: {
      background: '#7c3aed',
      objects: [
        {
          type: 'circle',
          left: 100,
          top: 100,
          radius: 30,
          fill: '#f472b6',
          opacity: 0.6,
        },
        {
          type: 'circle',
          left: 700,
          top: 150,
          radius: 50,
          fill: '#a78bfa',
          opacity: 0.5,
        },
        {
          type: 'circle',
          left: 150,
          top: 900,
          radius: 60,
          fill: '#60a5fa',
          opacity: 0.4,
        },
        {
          type: 'circle',
          left: 650,
          top: 850,
          radius: 40,
          fill: '#34d399',
          opacity: 0.6,
        },
        {
          type: 'text',
          left: 400,
          top: 150,
          text: '🎊 派对邀请 🎊',
          fontFamily: 'Impact',
          fontSize: 48,
          fill: '#fbbf24',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 230,
          text: 'YOU\'RE INVITED',
          fontFamily: 'Courier New',
          fontSize: 36,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 150,
          top: 320,
          width: 500,
          height: 3,
          fill: '#fbbf24',
        },
        {
          type: 'text',
          left: 400,
          top: 380,
          text: '周末狂欢夜',
          fontFamily: 'Georgia',
          fontSize: 42,
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
          fontStyle: 'italic',
        },
        {
          type: 'text',
          left: 400,
          top: 450,
          text: '时间：周六 20:00',
          fontFamily: 'Arial',
          fontSize: 24,
          fill: '#e9d5ff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 490,
          text: '地点：星光酒吧',
          fontFamily: 'Arial',
          fontSize: 24,
          fill: '#e9d5ff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 530,
          text: '着装要求：时尚休闲',
          fontFamily: 'Arial',
          fontSize: 24,
          fill: '#e9d5ff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 250,
          top: 600,
          width: 300,
          height: 60,
          fill: '#fbbf24',
          rx: 30,
          ry: 30,
        },
        {
          type: 'text',
          left: 400,
          top: 610,
          text: 'RSVP 请回复',
          fontFamily: 'Arial',
          fontSize: 24,
          fontWeight: 'bold',
          fill: '#7c3aed',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 700,
          text: '✨  🌟  💫  ⭐  ✨',
          fontFamily: 'Arial',
          fontSize: 32,
          fill: '#fbbf24',
          textAlign: 'center',
          originX: 'center',
        },
      ],
    },
  },
  {
    id: 'event',
    name: '活动宣传',
    category: '活动',
    thumbnail: '',
    data: {
      background: '#064e3b',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 800,
          height: 300,
          fill: 'linear-gradient(180deg, #064e3b 0%, #065f46 100%)',
          selectable: false,
          evented: false,
        },
        {
          type: 'text',
          left: 400,
          top: 80,
          text: '2024 年度盛典',
          fontFamily: 'Impact',
          fontSize: 56,
          fill: '#10b981',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 150,
          text: 'ANNUAL GALA',
          fontFamily: 'Courier New',
          fontSize: 28,
          fontWeight: 'bold',
          fill: '#6ee7b7',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 300,
          top: 210,
          width: 200,
          height: 5,
          fill: '#10b981',
        },
        {
          type: 'rect',
          left: 100,
          top: 350,
          width: 200,
          height: 150,
          fill: '#047857',
          rx: 12,
          ry: 12,
        },
        {
          type: 'text',
          left: 200,
          top: 380,
          text: '📅',
          fontFamily: 'Arial',
          fontSize: 40,
          fill: '#10b981',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 200,
          top: 430,
          text: '活动时间',
          fontFamily: 'Arial',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 200,
          top: 460,
          text: '12月25日 19:00',
          fontFamily: 'Arial',
          fontSize: 16,
          fill: '#a7f3d0',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 300,
          top: 350,
          width: 200,
          height: 150,
          fill: '#047857',
          rx: 12,
          ry: 12,
        },
        {
          type: 'text',
          left: 400,
          top: 380,
          text: '📍',
          fontFamily: 'Arial',
          fontSize: 40,
          fill: '#10b981',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 430,
          text: '活动地点',
          fontFamily: 'Arial',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 460,
          text: '国际会议中心',
          fontFamily: 'Arial',
          fontSize: 16,
          fill: '#a7f3d0',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 500,
          top: 350,
          width: 200,
          height: 150,
          fill: '#047857',
          rx: 12,
          ry: 12,
        },
        {
          type: 'text',
          left: 600,
          top: 380,
          text: '👥',
          fontFamily: 'Arial',
          fontSize: 40,
          fill: '#10b981',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 600,
          top: 430,
          text: '参与人数',
          fontFamily: 'Arial',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 600,
          top: 460,
          text: '限500人',
          fontFamily: 'Arial',
          fontSize: 16,
          fill: '#a7f3d0',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'rect',
          left: 200,
          top: 580,
          width: 400,
          height: 80,
          fill: '#10b981',
          rx: 40,
          ry: 40,
        },
        {
          type: 'text',
          left: 400,
          top: 600,
          text: '立即报名',
          fontFamily: 'Arial',
          fontSize: 32,
          fontWeight: 'bold',
          fill: '#ffffff',
          textAlign: 'center',
          originX: 'center',
        },
        {
          type: 'text',
          left: 400,
          top: 750,
          text: '精彩活动 · 丰厚奖品 · 难忘体验',
          fontFamily: 'Georgia',
          fontSize: 20,
          fontStyle: 'italic',
          fill: '#6ee7b7',
          textAlign: 'center',
          originX: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal',
    name: '简约风格',
    category: '简约',
    thumbnail: '',
    data: {
      background: '#ffffff',
      objects: [
        {
          type: 'rect',
          left: 60,
          top: 80,
          width: 4,
          height: 200,
          fill: '#4a90d9',
        },
        {
          type: 'text',
          left: 100,
          top: 100,
          text: '简约设计',
          fontFamily: 'Georgia',
          fontSize: 48,
          fontWeight: 'bold',
          fill: '#1e293b',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 100,
          top: 170,
          text: 'MINIMALIST DESIGN',
          fontFamily: 'Courier New',
          fontSize: 18,
          fill: '#64748b',
          textAlign: 'left',
        },
        {
          type: 'rect',
          left: 100,
          top: 220,
          width: 60,
          height: 3,
          fill: '#4a90d9',
        },
        {
          type: 'text',
          left: 100,
          top: 280,
          text: '少即是多',
          fontFamily: 'Georgia',
          fontSize: 28,
          fontStyle: 'italic',
          fill: '#475569',
          textAlign: 'left',
        },
        {
          type: 'text',
          left: 100,
          top: 330,
          text: 'Less is More',
          fontFamily: 'Georgia',
          fontSize: 24,
          fontStyle: 'italic',
          fill: '#94a3b8',
          textAlign: 'left',
        },
        {
          type: 'rect',
          left: 100,
          top: 420,
          width: 250,
          height: 250,
          fill: 'none',
          stroke: '#e2e8f0',
          strokeWidth: 2,
        },
        {
          type: 'rect',
          left: 130,
          top: 450,
          width: 190,
          height: 190,
          fill: '#f1f5f9',
        },
        {
          type: 'rect',
          left: 400,
          top: 420,
          width: 250,
          height: 250,
          fill: 'none',
          stroke: '#e2e8f0',
          strokeWidth: 2,
        },
        {
          type: 'rect',
          left: 430,
          top: 450,
          width: 190,
          height: 190,
          fill: '#4a90d9',
          opacity: 0.1,
        },
        {
          type: 'text',
          left: 100,
          top: 750,
          text: '简洁 · 优雅 · 纯粹',
          fontFamily: 'Arial',
          fontSize: 20,
          fill: '#64748b',
          textAlign: 'left',
        },
        {
          type: 'circle',
          left: 700,
          top: 150,
          radius: 40,
          fill: '#4a90d9',
          opacity: 0.1,
        },
        {
          type: 'circle',
          left: 720,
          top: 120,
          radius: 20,
          fill: '#4a90d9',
          opacity: 0.2,
        },
      ],
    },
  },
];
